sgas/apps/items/urls.py
from django.urls import path
from sgas.apps.items.views import CrearItem, ListarItem, ModificarItem, EliminarItem, verItem\
    , preAprobar, aprobarItem, desaprobarItem, verVersiones, versionesDetalles, ReversionarItem

urlpatterns = [
    path(r'nuevo/', CrearItem, name='crear_item'),
    path(r'listar/', ListarItem.as_view(), name='listar_items'),
    path(r'modificar/<int:idItem>/', ModificarItem, name='modificar_item'),
    path(r'eliminar/<int:idItem>/', EliminarItem, name='eliminar_item'),
    path(r'<int:idItem>/', verItem, name='ver_item'),
    path(r'<int:idItem>/versiones/', verVersiones, name='ver_versiones'),
    path(r'<int:idItem>/versiones/<int:idVersion>/', versionesDetalles, name='versiones_detalles'),
    path(r'<int:idItem>/versiones/<int:idVersion>/eliminar', ReversionarItem, name='restaurar_version'),
    path(r'preAprobar/<int:idItem>/', preAprobar, name='solicitar_aprobacion'),
    path(r'aprobar/<int:idItem>/', aprobarItem, name='aprobar_item'),
    path(r'desaprobar/<int:idItem>/', desaprobarItem, name='desaprobar_item'),
]

sgas/apps/miembros/urls.py
from django.conf.urls import url
from django.urls import path
from sgas.apps.roles.views import verRoles, asignarRol, desasignarRol
from sgas.apps.miembros.views import miembroCrear, verMiembrosEnProyecto, miembroEliminar

urlpatterns = [

    url(r'lista/', verMiembrosEnProyecto, name='lista'),
    url(r'nuevo/', miembroCrear, name='nuevo'),
    path('<int:idMiembro>/eliminar/', miembroEliminar, name='eliminar'),
    path('<int:idMiembro>/roles/', verRoles, name='ver_roles'),
    path('<int:idMiembro>/roles/<int:idRol>/asignar/', asignarRol, name='asignar_rol'),
    path('<int:idMiembro>/roles/<int:idRol>/desasignar/', desasignarRol, name='desasignar_rol'),
]

sgas/apps/proyectos/urls.py
from django.urls import path, include
from .views import ProyectoList, ProyectoCreate, ProyectoUpdate, index, createFases, updateFases, proyectoGeneral, fasesProyecto,\
    iniciarProyecto, cancelarProyecto, verFase, finalizarFase,verHistorial, asignarTI, comite, asignarComite, desasignarComite, verificarComite, finalizarProyecto, \
    crearLB, verLB, cerrarLB, crerSolicitud, interfazVotacion, votoAceptar, votoRechazar, verificarCambios, mantenerItem, cambiarItem, solicitudesProyecto, \
    reporteSolicitudes, reportes, reporteLB


urlpatterns = [
    # Enlace al menu principal de Proyectos
    path(r'', index, name='index'),
    path(r'listar/', ProyectoList.as_view(), name='listar_proyectos'),
    path(r'nuevo/', ProyectoCreate.as_view(), name='nuevo_proyecto'),
    path(r'<pk>/modificar/', ProyectoUpdate.as_view(), name='modificar_proyecto'),
    path(r'<int:id_proyecto>/', proyectoGeneral, name='general'),
    path(r'<int:id_proyecto>/iniciar/', iniciarProyecto, name='iniciar'),
    path(r'<int:id_proyecto>/finalizar/', finalizarProyecto, name='finalizar'),
    path(r'<int:id_proyecto>/cancelar/', cancelarProyecto, name='cancelar'),
    path(r'<int:id_proyecto>/fases', createFases, name='nuevas_fases'),
    path(r'<int:id_proyecto>/fases/modificar', updateFases, name='modificar_fases'),
    path(r'<int:id_proyecto>/fases/listar', fasesProyecto, name='listar_fases'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/', verFase, name='ver_fase'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/cerrar/', finalizarFase, name='cerrar_fase'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/', verLB, name='ver_lb'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/crearSolicitud/', crerSolicitud, name='crear_solicitud'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/crearLB/', crearLB, name='crear_LB'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/cerrar/', cerrarLB, name='cerrar_LB'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/tipoItem/<int:id_tipo>/', asignarTI, name='add_tipoItem'),
    path(r'<int:id_proyecto>/comite/', comite, name='comite'),
    path(r'<int:id_proyecto>/comite/nuevo/<int:id_usuario>', asignarComite, name='asignar_comite'),
    path(r'<int:id_proyecto>/comite/eliminar/<int:id_usuario>', desasignarComite, name='desasignar_comite'),
    path(r'<int:id_proyecto>/comite/verificar/', verificarComite, name='verificar_comite'),
    path(r'<int:id_proyecto>/solicitudes/', interfazVotacion, name='solicitudes_votacion'),
    path(r'<int:id_proyecto>/solicitudes/lista/', solicitudesProyecto, name='lista_solicitudes'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/aceptar/', votoAceptar, name='solicitudes_aceptar'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/rechazar/', votoRechazar, name='solicitudes_rechazar'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/cambios/', verificarCambios, name='verificar_cambios'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/mantener/<int:id_item>/', mantenerItem, name='cambios_mantener'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/cambiar/<int:id_item>/', cambiarItem, name='cambios_cambiar'),
    path(r'<int:id_proyecto>/historial/', verHistorial, name='ver_historial'),
    path(r'<int:id_proyecto>/reportes/', reportes, name='reportes'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/reporteLB/', reporteLB, name='reporte_LB'),
]

sgas/apps/roles/urls.py
from django.urls import path, include
from sgas.apps.roles.views import ListarRol, CrearRol, EliminarRol, EditarRol

urlpatterns = [
    path(r'listar/', ListarRol.as_view(), name='listar_roles'),
    path(r'nuevo/', CrearRol.as_view(), name='crear_rol'),
    path(r'eliminar/<int:id_rol>/', EliminarRol, name='eliminar_rol'),
    path(r'editar/<int:id_rol>/', EditarRol, name='editar_rol'),
]

sgas/apps/usuarios/urls.py
from django.urls import path, include

from sgas.apps.usuarios.views import home, CrearPerfil, ListarPerfil, editarPerfil, listaAcceso, \
    concederAcceso, eliminarPerfil, administrador, proyectos_usuario, bitacora

urlpatterns = [
    path(r'home/', home, name='home'),
    path(r'nuevo/', CrearPerfil.as_view(), name='crear_perfil'),
    path(r'listar/', ListarPerfil.as_view(), name='listar_perfiles'),
    path(r'acceso/', listaAcceso, name='lista_acceso'),
    path(r'administrador/<int:id_perfil>', concederAcceso, name='conceder_acceso'),
    path(r'editar/<int:id_perfil>/', editarPerfil, name='editar_perfil'),
    path(r'eliminar/<int:id_perfil>/', eliminarPerfil, name='eliminar_perfil'),
    path(r'administrador/', administrador, name='administrador'),
    path(r'<int:id_usuario>/', proyectos_usuario, name='proyectos_usuario'),
    path(r'<int:id_usuario>/bitacora/', bitacora, name='bitacora'),
]

sgas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # En este apartado se listan las urls predefinidas para el
    # autenticador de Google y urls del SGAS.
    #
    # 1. **URL** admin
    # 2. **URL** cuentas
    # 3. **URL** de proyectos
    # 4. **URL** de usuarios
    # 5. **URL** inicio

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('proyectos/', include(('sgas.apps.proyectos.urls', 'proyectos'), namespace='proyectos')),
    path('usuarios/', include(('sgas.apps.usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('', include('sgas.apps.proyectos.urls')),
    path('proyectos/<int:idProyecto>/miembros/', include(('sgas.apps.miembros.urls', 'miembros'), namespace='miembros')),
    path('proyectos/<int:idProyecto>/tipoitem/', include(('sgas.apps.tipoitem.urls', 'tipoitem'), namespace='tipoitem')),
    path('proyectos/<int:idProyecto>/roles/', include(('sgas.apps.roles.urls', 'roles'), namespace='roles')),
    path('proyectos/<int:idProyecto>/fases/<int:idFase>/tipoitem/<int:idTipo>/item/', include(('sgas.apps.items.urls', 'items'), namespace='items')),
    path('proyectos/<int:idProyecto>/fases/<int:idFase>/tipoitem/<int:idTipo>/item/<int:idItem>/relaciones/', include(('sgas.apps.relaciones.urls', 'relaciones'), namespace='relaciones')),
]

sgas/apps/miembros/models.py
from django.db import models
from sgas.apps.proyectos.models import Proyecto
from sgas.apps.usuarios.models import Perfil

# Create your models here.
class Miembro(models.Model):
    idPerfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    idProyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)

sgas/apps/relaciones/models.py
from django.db import models
from sgas.apps.items.models import Item

class Relacion(models.Model):
    itemA = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="itemA")
    itemB = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="itemB")
    tipo = models.IntegerField()

    def __str__(self):
        return str(self.itemA) + '->' + str(self.itemB)

sgas/apps/items/forms.py
from django import forms
from django.forms import modelformset_factory
from sgas.apps.items.models import Item, CampoNumero, CampoCadena, CampoFecha, CampoArchivo
from sgas.apps.tipoitem.models import TipoItem

class ItemForm(forms.ModelForm):

    identif = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "readonly": "readonly"}))

    def __init__(self, *args, **kwargs):
        nombre = kwargs.pop('nombre')
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['identif'].initial = nombre
        self.fields['costo'].widget.attrs['min'] = 1

    def save(self, commit=True, *args, **kwargs):
        fase = kwargs.get('fase')
        nombre = kwargs.get('nombre')
        tipo = kwargs.get('tipo')
        instance = super(ItemForm, self).save(commit=False)
        instance.fase = fase
        instance.identificador = nombre
        instance.tipo = tipo
        if commit:
            instance.save()
        return instance

    #def update(self, commit=True, *args, **kwargs):
    #    fase = kwargs.get('fase')
    #    nombre = kwargs.get('nombre')
    #    tipo = kwargs.get('tipo')
    #    version = kwargs.get('version')
    #    instance = super(ItemForm, self).save(commit=False)
    #    instance.fase = fase
    #    instance.identificador = nombre + "v" + str(version)
    #    instance.tipo = tipo
    #    instance.version = version
    #    if commit:
    #        instance.save()
    #    return instance

    def update(self, commit=True, *args, **kwargs):
        fase = kwargs.get('fase')
        nombre = kwargs.get('nombre')
        tipo = kwargs.get('tipo')
        version = kwargs.get('version')
        instance = super(ItemForm, self).save(commit=False)
        instance.fase = fase
        if version == 1:
            instance.identificador = nombre + "v" + str(version+1)
        else:
            n = len(nombre)
            instance.identificador = nombre[:n-1] + str(version+1)
        instance.tipo = tipo
        instance.version = version+1
        if commit:
            instance.save()
        return instance

    class Meta:

        model = Item

        fields = [
            'descripcion',
            'costo',
        ]
        labels = {
            'descripcion': 'Descripcion',
            'costo': 'Costo',
        }
        widgets = {
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
            'costo': forms.NumberInput(attrs={'initial': 0, 'min': 1, 'max': 10})
        }

class BaseCampoNumeroForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoNumeroForm, self).__init__(*args, **kwargs)

    class Meta:

        model = CampoNumero

        fields = [
            'nombre',
            'opcional',
            'numero'
        ]

class BaseCampoCadenaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoCadenaForm, self).__init__(*args, **kwargs)
        self.fields['cadena'].required = self.fields['opcional'].initial

    class Meta:
        model = CampoCadena

        fields = [
            'nombre',
            'opcional',
            'cadena'
        ]


class BaseCampoFechaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoFechaForm, self).__init__(*args, **kwargs)
        self.fields['fecha'].required = self.fields['opcional'].initial

    class Meta:
        model = CampoFecha

        fields = [
            'nombre',
            'opcional',
            'fecha'
        ]
        widgets={
            'fecha': forms.DateInput(attrs={'class':'form-control col-4','type':'date'})
        }
class BaseCampoArchivoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoArchivoForm, self).__init__(*args, **kwargs)
        self.fields['archivo'].required = self.fields['opcional'].initial

    class Meta:
        model = CampoArchivo

        fields = [
            'nombre',
            'opcional',
            'archivo'
        ]
        widgets = {
            'archivo': forms.FileInput(attrs={'class': 'custom-file'})
        }

class mensajeCorreo(forms.Form):
    mensaje = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows":"5"}))

sgas/apps/miembros/forms.py
from django import forms
from django.db.models import Q

from sgas.apps.miembros.models import Miembro
from sgas.apps.proyectos.models import Proyecto
from sgas.apps.usuarios.models import Perfil


class MiembrosForm(forms.ModelForm):

    class Meta:
            model = Miembro

            fields = [
                'idPerfil',
            ]

            labels = {
                'idPerfil': 'Perfil',
            }

            widgets = {
                'idPerfil': forms.Select(attrs={'class':'form-control custom-select'}),
            }


    def __init__(self, *args, **kwargs):
            idProyecto = kwargs.pop('idProyecto')
            super(MiembrosForm, self).__init__(*args, **kwargs)
            proyecto = Proyecto.objects.get(id=idProyecto)
            miembro = proyecto.miembro_set.all()
            perfil = Perfil.objects.all()
            valid_id = []
            for p in perfil:
                if not Miembro.objects.filter(idProyecto=proyecto).filter(idPerfil=p).exists():
                    if not p.id == 1:
                        valid_id.append(p.id)
            perfiles = Perfil.objects.filter(id__in = valid_id)
            self.fields['idPerfil'].queryset = perfiles

sgas/apps/miembros/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from sgas.apps.usuarios.models import Perfil
from sgas.apps.proyectos.models import Proyecto, Historial
from sgas.apps.miembros.models import Miembro
from sgas.apps.miembros.forms import MiembrosForm
from django.contrib.auth.models import User

# === Crear Miembro ===
@login_required
def miembroCrear(request, idProyecto):
    """
    Vista basada en funcion para crear miembros.
    Recibe un 'request' y la id de un Proyecto como parametros.
    Una vez haya terminado la peticion se retorna a la vista de Lista de Miembros.
    """
    if request.method == 'POST':
        form = MiembrosForm(request.POST, idProyecto=idProyecto)

        if form.is_valid():
            miembro = form.save(commit=False)
            miembro.idProyecto = Proyecto.objects.get(id=idProyecto)
            miembro.save()
            user = User.objects.get(username=request.user)
            perfil = Perfil.objects.get(user=user)
            Historial.objects.create(operacion='Agregar a {} al proyecto'.format(miembro.idPerfil.__str__()), autor=perfil.__str__(), proyecto=Proyecto.objects.get(id=idProyecto), categoria="Miembros")

        return redirect('miembros:lista', idProyecto=idProyecto)

    else:
        form = MiembrosForm(request.POST or None, idProyecto=idProyecto)

    return render(request, 'miembros/nuevoMiembro.html', {'form': form, 'proyecto':idProyecto})

# === Eliminar Miembro ===
@login_required
def miembroEliminar(request, idProyecto, idMiembro):
    """
    Vista basada en funcion para eliminar miembros.
    Recibe un 'request', el id de un proyecto y el id de un miembro como parametros.
    Una vez haya terminado la peticion se retorna a la vista de Lista de Miembros.
    """
    miembro = Miembro.objects.get(id=idMiembro)
    if request.method == 'POST':
        miembro.delete()
        user = User.objects.get(username=request.user)
        perfil = Perfil.objects.get(user=user)
        Historial.objects.create(operacion='Eliminar a {} del proyecto'.format(miembro.idPerfil.__str__()), autor=perfil.__str__(), proyecto=Proyecto.objects.get(id=idProyecto), categoria="Miembros")
        return redirect('miembros:lista', idProyecto=idProyecto)
    return render(request, 'miembros/eliminarMiembro.html', {'miembros':miembro, 'idProyecto':idProyecto})

# === Listar Miembros ===
@login_required
def verMiembrosEnProyecto(request, idProyecto):
    """
    Vista basada en funcion para listar miembros dentro de un proyecto.
    Recibe un 'request' y el id de un proyecto como parametros.
    """
    proyecto = Proyecto.objects.get(id=idProyecto)
    miembro = proyecto.miembro_set.all()
    perfil = Perfil.objects.all()
    valid_id = []
    for p in perfil:
        if not Miembro.objects.filter(idProyecto=proyecto).filter(idPerfil=p).exists():
            if not p.id == 1:
                valid_id.append(p.id)
    perfiles = Perfil.objects.filter(id__in = valid_id)
    #print(perfiles)
    miembro = Miembro.objects.filter(idProyecto=idProyecto)
    g = proyecto.gerente
    return render(request, 'miembros/verMiembrosEnProyecto.html', {'miembros':miembro, 'gerente':g, 'idProyecto':idProyecto, 'participantes_para_agregar':perfiles.all().count()>0})

sgas/templates/usuarios/administrador.html
{% extends 'base.html' %}
{% block content %}
<br>
<div class="container-fluid">
    <h2 align="center">Administración del Sistema</h2><br>
    <div class="row">
        <div class="col-md-5">
            <ins><h3 align="center">Proyectos</h3></ins>
            {% if proyectos %}
                <table class="table">
                    <thead>
                        <tr class="table-primary">
                            <td>ID</td>
                            <td>Nombre</td>
                            <td>Gerente</td>
                            <td> Descripción </td>
                            <td>Estado</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for proyecto in proyectos %}
                        <tr>
                            <td>{{proyecto.id}}</td>
                            <td>{{proyecto.nombre}}</td>
                            <td>{{proyecto.gerente}}</td>
                            <td>{{proyecto.descripcion}}</td>
                            <td>{{proyecto.estado}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="float-right">
                    <a class="btn btn-primary" role="button" href="{% url 'proyectos:nuevo_proyecto' %}" >Crear Proyecto</a>
                    <a class="btn btn-info" role="button" href="{% url 'proyectos:listar_proyectos' %}">Ver más</a>
                </div>
            {% else %}
                <h4>Aún no existen proyectos creados</h4>
                <a class="btn btn-primary" role="button" href="{% url 'proyectos:nuevo_proyecto' %}" >Crear Proyecto</a>
            {% endif %}
        </div>
        <div class="col-md-5">
            <ins><h3 align="center">Solicitudes de Acceso</h3></ins>
            {% if perfilesAcceso %}
                <table class="table">
                    <thead>
                        <tr class="table-primary">
                            <th scope="col">Id</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">CI</th>
                            <th scope="col">Acceso</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for perfil in perfilesAcceso %}
                            <tr>
                                <td style="vertical-align:middle;">{{perfil.id}}</td>
                                <td style="vertical-align:middle;">{{perfil.user.first_name}}</td>
                                <td style="vertical-align:middle;">{{perfil.user.last_name}} </td>
                                <td style="vertical-align:middle;">{{perfil.ci}}</td>
                                <td><a href="{% url 'usuarios:conceder_acceso' perfil.id%}" class="btn btn-primary" role="button">Conceder</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>No hay solicitudes de acceso al sistema</h4>
            {% endif %}
        </div>
        <div class="col-md-2">
            <a class="btn btn-info btn-lg btn-block" href="{% url 'usuarios:listar_perfiles' %}">Ver Usuarios</a>
        </div>
    </div>
</div> <br><br>
{% endblock %}

sgas/templates/usuarios/bitacora.html
{% extends 'base.html' %}
{% load filtros_proyectos %}

{% block content %}
<br>
<div class="container-fluid">
    <ins><h3 align="center">Proyectos de {{request.user.first_name}}</h3></ins>
        <br>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row">
        {% if dict %}
            {% for key, value in dict.items %}
                <div class="col mt-3">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{key.nombre}}</h4>
                        <h6 class="card-subtitle mb-2 text-muted">Estado: {{key.estado}}</h6>
                        <p class="card-text"><b>Gerente:</b> {{key.gerente}}</p>
                        <p class="card-text"><b>Mis roles:</b></p>
                            <ul>
                            {% for rol in value %}
                        <li>{{rol.nombre}} en {% for fase in rol.fase.all %} {{fase.nombre}} {% endfor %}</li>
                            {% endfor %}</ul>
                        <p align="right">
                        <a href="{% url 'proyectos:general' key.id %}" class="card-link">Ir al proyecto</a></p>
                    </div>
                </div>
                    </div>
            {% if forloop.counter|separacion:2 %}
                <div class="w-100"></div>
            {% endif %}
            {% endfor %}
        {% else %}
            <h4>Aún no participó en ningún proyecto</h4>
        {% endif %}
                </div>
         </div>
         <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

sgas/templates/usuarios/listar_perfiles.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
    <ins><h3 align="center">Usuarios del Sistema</h3></ins>
    <br>
    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-10">
            {% if object_list %}
          <table class="table">
                <thead>
                    <tr class="table-primary">
                        <th scope="col">Id</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">Email</th>
                        <th scope="col">CI</th>
                        <th scope="col">Teléfono</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
            {% if messages %}
                    {% for message in messages %}
                        {% if 'error' in message.tags %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
            {% endif %}
                {% for perfil in object_list %}
                    <tr>
                        <td>{{perfil.id}}</td>
                        <td>{{perfil.user.first_name}}</td>
                        <td>{{perfil.user.last_name}} </td>
                        <td>{{perfil.user.email}}</td>
                        <td>{{perfil.ci}}</td>
                        <td>{{perfil.telefono}}</td>
                        <td><a class="btn btn-primary" role="button" href="{% url 'usuarios:editar_perfil' perfil.id %}">Editar</a>
                        <a class="btn btn-danger" role="button" href="{% url 'usuarios:eliminar_perfil' perfil.id %}">Eliminar</a></td>
                    </tr>
                {% endfor %}
            </tbody>
         </table>
            <p align="center">
                <a class="btn btn-primary" role="button" href="{% url 'usuarios:administrador'%}">Volver</a>
            </p>
               {% else %}
                <h1>No hay perfiles</h1>
            {% endif %}
        </div>
        <div class="col-md-1">

        </div>
    </div>
</div>
{% endblock %}

sgas/templates/usuarios/proyectos.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container-fluid">
    <ins><h3 align="center">Proyectos Asociados</h3></ins>
    <br>
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            {% if miembros %}
                <table class="table">
                    <thead>
                        <tr class="table-primary">
                            <td>ID</td>
                            <td>Nombre</td>
                            <td>Gerente</td>
                            <td>Descripción</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for miembro in miembros %}
                            <tr>
                                <td>{{ miembro.idProyecto.id }}</td>
                                <td><a href="{% url 'proyectos:general' miembro.idProyecto.id %}">{{ miembro.idProyecto.nombre }}</a></td>
                                <td>{{miembro.idProyecto.gerente}}</td>
                                <td>{{ miembro.idProyecto.descripcion }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
            </table>
            {% else %}
                <h3>Aún no posee proyectos asociados</h3>
            {% endif %}
        </div>
        <div class="col-md-3">

        </div>
    </div>
    <p align="center">
        <a class="btn btn-primary" role="button" href="{% url 'usuarios:home'%}">Volver</a>
    </p>
</div>
{% endblock %}

sgas/templates/usuarios/usuario_acceso.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
    {% if perfiles %}
    <table class="table">
        <thead>
            <tr class="table-primary">
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Email</th>
                <th scope="col">CI</th>
                <th scope="col">Teléfono</th>
                <th scope="col">Acceso</th>
            </tr>
        </thead>
        <tbody>
                {% for perfil in perfiles %}
                    <tr>
                        <td style="vertical-align:middle;">{{perfil.id}}</td>
                        <td style="vertical-align:middle;">{{perfil.user.first_name}}</td>
                        <td style="vertical-align:middle;">{{perfil.user.last_name}} </td>
                        <td style="vertical-align:middle;">{{perfil.user.email}}</td>
                        <td style="vertical-align:middle;">{{perfil.ci}}</td>
                        <td style="vertical-align:middle;">{{perfil.telefono}}</td>
                        <td><a href="{% url 'usuarios:conceder_acceso' perfil.id%}" class="btn btn-primary" role="button">Conceder</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <h2>No hay solicitudes de acceso al sistema</h2>
                <a href="{% url 'usuarios:home' %}" class="btn btn-primary btn-lg">Volver</a>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}