sgas/apps/items/urls.py
from django.urls import path
from sgas.apps.items.views import CrearItem, ListarItem, ModificarItem, EliminarItem, verItem\
    , preAprobar, aprobarItem, desaprobarItem, verVersiones, versionesDetalles, ReversionarItem

urlpatterns = [
    path(r'nuevo/', CrearItem, name='crear_item'),
    path(r'listar/', ListarItem.as_view(), name='listar_items'),
    path(r'modificar/<int:idItem>/', ModificarItem, name='modificar_item'),
    path(r'eliminar/<int:idItem>/', EliminarItem, name='eliminar_item'),
    path(r'<int:idItem>/', verItem, name='ver_item'),
    path(r'<int:idItem>/versiones/', verVersiones, name='ver_versiones'),
    path(r'<int:idItem>/versiones/<int:idVersion>/', versionesDetalles, name='versiones_detalles'),
    path(r'<int:idItem>/versiones/<int:idVersion>/eliminar', ReversionarItem, name='restaurar_version'),
    path(r'preAprobar/<int:idItem>/', preAprobar, name='solicitar_aprobacion'),
    path(r'aprobar/<int:idItem>/', aprobarItem, name='aprobar_item'),
    path(r'desaprobar/<int:idItem>/', desaprobarItem, name='desaprobar_item'),
]

sgas/apps/miembros/urls.py
from django.conf.urls import url
from django.urls import path
from sgas.apps.roles.views import verRoles, asignarRol, desasignarRol
from sgas.apps.miembros.views import miembroCrear, verMiembrosEnProyecto, miembroEliminar

urlpatterns = [

    url(r'lista/', verMiembrosEnProyecto, name='lista'),
    url(r'nuevo/', miembroCrear, name='nuevo'),
    path('<int:idMiembro>/eliminar/', miembroEliminar, name='eliminar'),
    path('<int:idMiembro>/roles/', verRoles, name='ver_roles'),
    path('<int:idMiembro>/roles/<int:idRol>/asignar/', asignarRol, name='asignar_rol'),
    path('<int:idMiembro>/roles/<int:idRol>/desasignar/', desasignarRol, name='desasignar_rol'),
]

sgas/apps/proyectos/urls.py
from django.urls import path, include
from .views import ProyectoList, ProyectoCreate, ProyectoUpdate, index, createFases, updateFases, proyectoGeneral, fasesProyecto,\
    iniciarProyecto, cancelarProyecto, verFase, finalizarFase,verHistorial, asignarTI, comite, asignarComite, desasignarComite, verificarComite, finalizarProyecto, \
    crearLB, verLB, cerrarLB, crerSolicitud, interfazVotacion, votoAceptar, votoRechazar, verificarCambios, mantenerItem, cambiarItem, solicitudesProyecto, \
    reporteSolicitudes, reportes, reporteLB


urlpatterns = [
    # Enlace al menu principal de Proyectos
    path(r'', index, name='index'),
    path(r'listar/', ProyectoList.as_view(), name='listar_proyectos'),
    path(r'nuevo/', ProyectoCreate.as_view(), name='nuevo_proyecto'),
    path(r'<pk>/modificar/', ProyectoUpdate.as_view(), name='modificar_proyecto'),
    path(r'<int:id_proyecto>/', proyectoGeneral, name='general'),
    path(r'<int:id_proyecto>/iniciar/', iniciarProyecto, name='iniciar'),
    path(r'<int:id_proyecto>/finalizar/', finalizarProyecto, name='finalizar'),
    path(r'<int:id_proyecto>/cancelar/', cancelarProyecto, name='cancelar'),
    path(r'<int:id_proyecto>/fases', createFases, name='nuevas_fases'),
    path(r'<int:id_proyecto>/fases/modificar', updateFases, name='modificar_fases'),
    path(r'<int:id_proyecto>/fases/listar', fasesProyecto, name='listar_fases'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/', verFase, name='ver_fase'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/cerrar/', finalizarFase, name='cerrar_fase'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/', verLB, name='ver_lb'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/crearSolicitud/', crerSolicitud, name='crear_solicitud'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/crearLB/', crearLB, name='crear_LB'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/cerrar/', cerrarLB, name='cerrar_LB'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/tipoItem/<int:id_tipo>/', asignarTI, name='add_tipoItem'),
    path(r'<int:id_proyecto>/comite/', comite, name='comite'),
    path(r'<int:id_proyecto>/comite/nuevo/<int:id_usuario>', asignarComite, name='asignar_comite'),
    path(r'<int:id_proyecto>/comite/eliminar/<int:id_usuario>', desasignarComite, name='desasignar_comite'),
    path(r'<int:id_proyecto>/comite/verificar/', verificarComite, name='verificar_comite'),
    path(r'<int:id_proyecto>/solicitudes/', interfazVotacion, name='solicitudes_votacion'),
    path(r'<int:id_proyecto>/solicitudes/lista/', solicitudesProyecto, name='lista_solicitudes'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/aceptar/', votoAceptar, name='solicitudes_aceptar'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/rechazar/', votoRechazar, name='solicitudes_rechazar'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/cambios/', verificarCambios, name='verificar_cambios'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/mantener/<int:id_item>/', mantenerItem, name='cambios_mantener'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/cambiar/<int:id_item>/', cambiarItem, name='cambios_cambiar'),
    path(r'<int:id_proyecto>/historial/', verHistorial, name='ver_historial'),
    path(r'<int:id_proyecto>/reportes/', reportes, name='reportes'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/reporteLB/', reporteLB, name='reporte_LB'),
]

sgas/apps/relaciones/urls.py
from django.conf.urls import url
from django.urls import path

from sgas.apps.relaciones.views import crearRelacionAS, crearRelacionPH, eliminarRelacion, calcularImpacto, trazarItem

urlpatterns = [

    #url(r'lista/', listaRelaciones, name='lista'),
    url(r'nuevoAS/', crearRelacionAS, name='nuevoAS'),
    url(r'nuevoPH/', crearRelacionPH, name='nuevoPH'),
    url(r'impacto/', calcularImpacto, name='impacto'),
    url(r'trazabilidad/', trazarItem, name='trazabilidad'),
    path('eliminar/<int:idRelacion>/', eliminarRelacion, name='eliminar'),

]

sgas/apps/roles/urls.py
from django.urls import path, include
from sgas.apps.roles.views import ListarRol, CrearRol, EliminarRol, EditarRol

urlpatterns = [
    path(r'listar/', ListarRol.as_view(), name='listar_roles'),
    path(r'nuevo/', CrearRol.as_view(), name='crear_rol'),
    path(r'eliminar/<int:id_rol>/', EliminarRol, name='eliminar_rol'),
    path(r'editar/<int:id_rol>/', EditarRol, name='editar_rol'),
]

sgas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # En este apartado se listan las urls predefinidas para el
    # autenticador de Google y urls del SGAS.
    #
    # 1. **URL** admin
    # 2. **URL** cuentas
    # 3. **URL** de proyectos
    # 4. **URL** de usuarios
    # 5. **URL** inicio

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('proyectos/', include(('sgas.apps.proyectos.urls', 'proyectos'), namespace='proyectos')),
    path('usuarios/', include(('sgas.apps.usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('', include('sgas.apps.proyectos.urls')),
    path('proyectos/<int:idProyecto>/miembros/', include(('sgas.apps.miembros.urls', 'miembros'), namespace='miembros')),
    path('proyectos/<int:idProyecto>/tipoitem/', include(('sgas.apps.tipoitem.urls', 'tipoitem'), namespace='tipoitem')),
    path('proyectos/<int:idProyecto>/roles/', include(('sgas.apps.roles.urls', 'roles'), namespace='roles')),
    path('proyectos/<int:idProyecto>/fases/<int:idFase>/tipoitem/<int:idTipo>/item/', include(('sgas.apps.items.urls', 'items'), namespace='items')),
    path('proyectos/<int:idProyecto>/fases/<int:idFase>/tipoitem/<int:idTipo>/item/<int:idItem>/relaciones/', include(('sgas.apps.relaciones.urls', 'relaciones'), namespace='relaciones')),
]

sgas/apps/items/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

ESTADO_CHOICES = [
    ("En Desarrollo", "En Desarrollo"),
    ("Aprobado", "Aprobado"),
    ("En LB", "En LB"),
    ("En Revision", "En Revision"),
    ("Desactivado", "Desactivado"),
    ("Para aprobar", "Para aprobar")
]
class Item(models.Model):
    fase = models.ForeignKey(to='proyectos.Fase', on_delete=models.CASCADE, null=True)
    identificador = models.CharField(max_length=80, null=True)
    tipo = models.ForeignKey(to='tipoitem.TipoItem', on_delete=models.CASCADE, null=True)
    version = models.PositiveIntegerField(default=1)
    costo = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    estado = models.CharField(max_length=80, choices=ESTADO_CHOICES, default="En Desarrollo")
    descripcion = models.CharField(max_length=80)

    class Meta:

        unique_together = ['identificador', 'fase']

    def __str__(self):
        return '{}'.format(self.identificador)

class CampoNumero(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=80, null=True, blank=True)
    numero = models.FloatField(null=True, blank=True)
    opcional = models.BooleanField(null=True, blank=True)

class CampoCadena(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=80, null=True, blank=True)
    cadena = models.CharField(max_length=80)
    opcional = models.BooleanField(null=True, blank=True)

class CampoFecha(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=80, null=True, blank=True)
    fecha = models.DateField(null=True, blank=True)
    opcional = models.BooleanField(null=True, blank=True)

class CampoArchivo(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=80, null=True, blank=True)
    archivo =  models.FileField(upload_to='adjuntos/', null=True, blank=True)
    opcional = models.BooleanField(null=True, blank=True)

class Version(models.Model):
    itemBase = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="itemBase")

    fase = models.ForeignKey(to='proyectos.Fase', on_delete=models.CASCADE, null=True)
    identificador = models.CharField(max_length=80, null=True)
    tipo = models.ForeignKey(to='tipoitem.TipoItem', on_delete=models.CASCADE, null=True)
    version = models.PositiveIntegerField(default=1)
    costo = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    estado = models.CharField(max_length=80, choices=ESTADO_CHOICES, default="En Desarrollo")
    descripcion = models.CharField(max_length=80)

    ccNumero = models.TextField()
    ccCadena = models.TextField()
    ccFecha = models.TextField()
    ccArchivo = models.TextField()

    ccRelaciones = models.TextField()

    def versionar(self, itemId):
        it = Item.objects.get(id=itemId)

        # Copia de atributos base del item
        self.itemBase = it
        self.fase = it.fase
        self.identificador = it.identificador
        self.tipo = it.tipo
        self.version = it.version
        self.costo = it.costo
        self.estado = it.estado
        self.descripcion = it.descripcion

        # Copia de atributos adicionales
        numeros = CampoNumero.objects.filter(item=it)
        cadenas = CampoCadena.objects.filter(item=it)
        fechas = CampoFecha.objects.filter(item=it)
        archivos = CampoArchivo.objects.filter(item=it)

        dictN = {}
        dictC = {}
        dictF = {}
        dictA = {}

        for i in range(len(numeros)):
            dictAux = {}
            dictAux['nombre'] = numeros[i].nombre
            dictAux['numero'] = str(numeros[i].numero)
            dictAux['opcional'] = str(numeros[i].opcional)

            dictN[str(i)] = dictAux

        for i in range(len(cadenas)):
            dictAux = {}
            dictAux['nombre'] = cadenas[i].nombre
            dictAux['cadena'] = cadenas[i].cadena
            dictAux['opcional'] = str(cadenas[i].opcional)

            dictC[str(i)] = dictAux

        for i in range(len(fechas)):
            dictAux = {}
            dictAux['nombre'] = fechas[i].nombre
            dictAux['fecha'] = str(fechas[i].fecha)
            dictAux['opcional'] = str(fechas[i].opcional)

            dictF[str(i)] = dictAux

        for i in range(len(archivos)):
            dictAux = {}
            dictAux['nombre'] = archivos[i].nombre
            dictAux['archivo'] = str(archivos[i].archivo)
            dictAux['opcional'] = str(archivos[i].opcional)

            dictA[str(i)] = dictAux

        self.ccNumero = dictN
        self.ccCadena = dictC
        self.ccFecha = dictF
        self.ccArchivo = dictA

        # Copia de relaciones
        relacionesA = it.itemA.all()
        relacionesB = it.itemB.all()

        dictR = {}

        dictRA = {}
        dictRB = {}

        for i in range(len(relacionesA)):
            dictAux = {}
            dictAux['id'] = str(relacionesA[i].id)
            dictAux['tipo'] = str(relacionesA[i].tipo)
            dictAux['itemA'] = str(relacionesA[i].itemA.id)
            dictAux['itemAnombre'] = relacionesA[i].itemA.identificador
            dictAux['itemB'] = str(relacionesA[i].itemB.id)
            dictAux['itemBnombre'] = relacionesA[i].itemB.identificador

            dictRA[str(i)] = dictAux

        for i in range(len(relacionesB)):
            dictAux = {}
            dictAux['id'] = str(relacionesB[i].id)
            dictAux['tipo'] = str(relacionesB[i].tipo)
            dictAux['itemA'] = str(relacionesB[i].itemA.id)
            dictAux['itemAnombre'] = relacionesB[i].itemA.identificador
            dictAux['itemB'] = str(relacionesB[i].itemB.id)
            dictAux['itemBnombre'] = relacionesB[i].itemB.identificador

            dictRB[str(i)] = dictAux

        dictR['0'] = dictRA
        dictR['1'] = dictRB

        self.ccRelaciones = dictR

        self.save()

sgas/apps/miembros/models.py
from django.db import models
from sgas.apps.proyectos.models import Proyecto
from sgas.apps.usuarios.models import Perfil

# Create your models here.
class Miembro(models.Model):
    idPerfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    idProyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)

sgas/apps/relaciones/models.py
from django.db import models
from sgas.apps.items.models import Item

class Relacion(models.Model):
    itemA = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="itemA")
    itemB = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="itemB")
    tipo = models.IntegerField()

    def __str__(self):
        return str(self.itemA) + '->' + str(self.itemB)

sgas/apps/miembros/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from sgas.apps.usuarios.models import Perfil
from sgas.apps.proyectos.models import Proyecto, Historial
from sgas.apps.miembros.models import Miembro
from sgas.apps.miembros.forms import MiembrosForm
from django.contrib.auth.models import User

# === Crear Miembro ===
@login_required
def miembroCrear(request, idProyecto):
    """
    Vista basada en funcion para crear miembros.
    Recibe un 'request' y la id de un Proyecto como parametros.
    Una vez haya terminado la peticion se retorna a la vista de Lista de Miembros.
    """
    if request.method == 'POST':
        form = MiembrosForm(request.POST, idProyecto=idProyecto)

        if form.is_valid():
            miembro = form.save(commit=False)
            miembro.idProyecto = Proyecto.objects.get(id=idProyecto)
            miembro.save()
            user = User.objects.get(username=request.user)
            perfil = Perfil.objects.get(user=user)
            Historial.objects.create(operacion='Agregar a {} al proyecto'.format(miembro.idPerfil.__str__()), autor=perfil.__str__(), proyecto=Proyecto.objects.get(id=idProyecto), categoria="Miembros")

        return redirect('miembros:lista', idProyecto=idProyecto)

    else:
        form = MiembrosForm(request.POST or None, idProyecto=idProyecto)

    return render(request, 'miembros/nuevoMiembro.html', {'form': form, 'proyecto':idProyecto})

# === Eliminar Miembro ===
@login_required
def miembroEliminar(request, idProyecto, idMiembro):
    """
    Vista basada en funcion para eliminar miembros.
    Recibe un 'request', el id de un proyecto y el id de un miembro como parametros.
    Una vez haya terminado la peticion se retorna a la vista de Lista de Miembros.
    """
    miembro = Miembro.objects.get(id=idMiembro)
    if request.method == 'POST':
        miembro.delete()
        user = User.objects.get(username=request.user)
        perfil = Perfil.objects.get(user=user)
        Historial.objects.create(operacion='Eliminar a {} del proyecto'.format(miembro.idPerfil.__str__()), autor=perfil.__str__(), proyecto=Proyecto.objects.get(id=idProyecto), categoria="Miembros")
        return redirect('miembros:lista', idProyecto=idProyecto)
    return render(request, 'miembros/eliminarMiembro.html', {'miembros':miembro, 'idProyecto':idProyecto})

# === Listar Miembros ===
@login_required
def verMiembrosEnProyecto(request, idProyecto):
    """
    Vista basada en funcion para listar miembros dentro de un proyecto.
    Recibe un 'request' y el id de un proyecto como parametros.
    """
    proyecto = Proyecto.objects.get(id=idProyecto)
    miembro = proyecto.miembro_set.all()
    perfil = Perfil.objects.all()
    valid_id = []
    for p in perfil:
        if not Miembro.objects.filter(idProyecto=proyecto).filter(idPerfil=p).exists():
            if not p.id == 1:
                valid_id.append(p.id)
    perfiles = Perfil.objects.filter(id__in = valid_id)
    #print(perfiles)
    miembro = Miembro.objects.filter(idProyecto=idProyecto)
    g = proyecto.gerente
    return render(request, 'miembros/verMiembrosEnProyecto.html', {'miembros':miembro, 'gerente':g, 'idProyecto':idProyecto, 'participantes_para_agregar':perfiles.all().count()>0})

sgas/templates/items/desaprobar_item.html
{% extends 'base.html' %}
{% block content %}
<br>
<div class="container-fluid">
    <h3 align="center">Está por desaprobar el item {{item.identificador}}</h3>
    <h5 align="center">Por favor indique el motivo de manera a notificar a los desarrolladores</h5>
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4">
            <form class=form-horizontal" method="POST">
                {% csrf_token %}
                {{mensaje.mensaje}}
                <br>
                <p align="center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{% url 'items:listar_items' idProyecto idFase idTipo%}" class="btn btn-danger" role="button">Cancelar</a>
                </p>
            </form>
        </div>
        <div class="col-md-4">

        </div>
    </div>
</div>
{% endblock %}

sgas/templates/items/restaurar_version.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12"><center>
            <form method="POST">
                {% csrf_token %}
                <h3>Estas seguro de que quieres volver a esta version del item {{ver.itemBase.identificador}} ?</h3>

                <button type="submit" class="btn btn-danger">Confirmar</button>
                <a class="btn btn-primary" href="{% url 'items:listar_items' idProyecto idFase idTipo %}">Cancelar</a>
            </form>
        </center></div>
    </div>
</div>
{% endblock %}

sgas/templates/items/ver_item.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}
<br>
<div class="container-fluid">
    {% if messages %}
                    {% for message in messages %}
                        {% if 'error' in message.tags %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
            {% endif %}
    <h3 align="center">Item: {{item.identificador}}</h3>
    <br>
    <div class="row">
        <div class="col-md-6">
            <ins><h4 align="center">Información General</h4></ins>
            <table class="table table-light">
                <tbody>
                    <tr>
                        <th class="table-primary">Identificador:</th>
                        <td>{{item.identificador}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Descripción:</th>
                        <td>{{item.descripcion}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Tipo de Ítem:</th>
                        <td>{{item.tipo.nombre}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Versión:</th>
                        <td>{{item.version}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Costo:</th>
                        <td>{{item.costo}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Estado:</th>
                        <td>{{item.estado}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <ins><h4 align="center">Relaciones</h4></ins>
            <table class="table">
                <tbody>
                    {% for rA in relacionA %}
                    <tr>
                        {% if rA.tipo == 1 %}
                            <td>Relación Antecesor->Sucesor</td>
                        {% else %}
                            <td>Relación Padre->Hijo</td>
                        {% endif%}
                        <td> <center><b>{{ rA.itemA.identificador }}</b> -> {{ rA.itemB.identificador }}</center> </td>
                        {% if item.id == rA.itemB.id and request.user|eliminar_relacion:item.fase.id and item.estado == 'En Desarrollo' %}
                            <td> <a class="btn btn-danger" href="{% url 'relaciones:eliminar' idProyecto idFase idTipo idItem rA.id %}">Eliminar</a> </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    {% for rB in relacionB %}
                    <tr>
                        {% if rB.tipo == 1 %}
                            <td>Relación Antecesor->Sucesor</td>
                        {% else %}
                            <td>Relación Padre->Hijo</td>
                        {% endif%}
                        <td> <center>{{ rB.itemA.identificador }} -> <b>{{ rB.itemB.identificador }}</b></center> </td>
                        {% if item.id == rB.itemB.id and request.user|eliminar_relacion:item.fase.id and item.estado == 'En Desarrollo' %}
                            <td> <a class="btn btn-danger" href="{% url 'relaciones:eliminar' idProyecto idFase idTipo idItem rB.id %}">Eliminar</a> </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" align="right">
        <div class="col-md-12">
            {% if fase.estado == 'Abierta' %}
                {% if item.estado == 'En Desarrollo'%}
                    {% if request.user|crear_item:item.fase.id or request.user|modificar_item:item.fase.id  %}
                        <a href="{% url 'items:solicitar_aprobacion' item.fase.proyecto.id item.fase.id item.tipo.id item.id %}" class="btn btn-success">Solicitar Aprobación</a>
                    {% endif %}
                {% endif %}
                {% if item.estado == 'En Desarrollo' and request.user|modificar_item:item.fase.id %}
                    <a href="{% url 'items:modificar_item' idProyecto idFase idTipo item.id %}" class="btn btn-primary">Modificar</a>
                {% endif %}
                {% if item.estado == 'Para aprobar' and request.user|aprobar_item:item.fase.id %}
                    <a href="{% url 'items:aprobar_item' item.fase.proyecto.id item.fase.id item.tipo.id item.id %}" class="btn btn-success">Aprobar</a>
                {% endif %}
                {% if item.estado == 'Para aprobar' and request.user|desaprobar_item:item.fase.id %}
                    <a href="{% url 'items:desaprobar_item' item.fase.proyecto.id item.fase.id item.tipo.id item.id %}" class="btn btn-danger">Desaprobar</a>
                {% endif %}
                {% if item.fase.posicion > 1 and item.estado == 'En Desarrollo' and request.user|relacionar_AS:item.fase.id %}
                    <a href="{% url 'relaciones:nuevoAS' idProyecto idFase idTipo idItem %}" class="btn btn-primary">Relacionar AS</a>
                {% endif %}
                {% if item.estado == 'En Desarrollo' and request.user|relacionar_PH:item.fase.id %}
                    <a href="{% url 'relaciones:nuevoPH' idProyecto idFase idTipo idItem %}" class="btn btn-primary">Relacionar PH</a>
                {% endif %}
                {% if item.estado == 'En Desarrollo' and  request.user|desactivar_item:item.fase.id %}
                    <a href="{% url 'items:eliminar_item' idProyecto idFase idTipo item.id %}" class="btn btn-danger">Eliminar</a>
                {% endif %}
                {% if item.estado == 'En Desarrollo' %}
                  <a href="{% url 'items:ver_versiones' idProyecto idFase idTipo item.id %}" class="btn btn-primary">Restaurar</a>
                {% endif %}
            {% endif %}
            <a href="{% url 'relaciones:impacto' idProyecto idFase idTipo item.id %}" class="btn btn-primary">Impacto</a>
            <a href="{% url 'relaciones:trazabilidad' idProyecto idFase idTipo item.id %}" class="btn btn-primary">Trazabilidad</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" align="center">
            <br>
            <a href="{% url 'items:listar_items' item.fase.proyecto.id item.fase.id item.tipo.id %}" class="btn btn-primary">Volver</a>
        </div>
    </div>
</div>
{% endblock %}

sgas/templates/items/ver_versiones.html
{% extends 'base.html' %}

{% block content %}

<br>
<div class="container-fluid">
    <ins><h3 align="center">Versiones Anteriores</h3></ins>
    <br>
    <div class="row">
        <div class="col-md-1">

        </div>
        <div class="col-md-10">
            {% if cantidad %}
                <table class="table">
                    <thead>
                        <tr class="table-primary">
                            <th scope="col">Identificador</th>
                            <th scope="col">Descripcion</th>
                            <th scope="col">Version</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for v in versiones %}
                            <tr>
                                <td scope="col">{{v.identificador}}</td>
                                <td scope="col">{{v.descripcion}}</td>
                                <td scope="col">{{v.version}}</td>
                                <td scope="col"><a href="{% url 'items:versiones_detalles' idProyecto idFase idTipo v.itemBase.id v.id %}">Mas detalles</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            <p align="center">
                <a href="{% url 'items:listar_items' idProyecto idFase idTipo %}" class="btn btn-primary" role="button">Volver</a>
            </p>
        </div>
        <div class="col-md-1">

        </div>
    </div>
</div>

{% endblock %}