sgas/apps/items/urls.py
from django.urls import path
from sgas.apps.items.views import CrearItem, ListarItem, ModificarItem, EliminarItem, verItem\
    , preAprobar, aprobarItem, desaprobarItem, verVersiones, versionesDetalles, ReversionarItem

urlpatterns = [
    path(r'nuevo/', CrearItem, name='crear_item'),
    path(r'listar/', ListarItem.as_view(), name='listar_items'),
    path(r'modificar/<int:idItem>/', ModificarItem, name='modificar_item'),
    path(r'eliminar/<int:idItem>/', EliminarItem, name='eliminar_item'),
    path(r'<int:idItem>/', verItem, name='ver_item'),
    path(r'<int:idItem>/versiones/', verVersiones, name='ver_versiones'),
    path(r'<int:idItem>/versiones/<int:idVersion>/', versionesDetalles, name='versiones_detalles'),
    path(r'<int:idItem>/versiones/<int:idVersion>/eliminar', ReversionarItem, name='restaurar_version'),
    path(r'preAprobar/<int:idItem>/', preAprobar, name='solicitar_aprobacion'),
    path(r'aprobar/<int:idItem>/', aprobarItem, name='aprobar_item'),
    path(r'desaprobar/<int:idItem>/', desaprobarItem, name='desaprobar_item'),
]

sgas/apps/miembros/urls.py
from django.conf.urls import url
from django.urls import path
from sgas.apps.roles.views import verRoles, asignarRol, desasignarRol
from sgas.apps.miembros.views import miembroCrear, verMiembrosEnProyecto, miembroEliminar

urlpatterns = [

    url(r'lista/', verMiembrosEnProyecto, name='lista'),
    url(r'nuevo/', miembroCrear, name='nuevo'),
    path('<int:idMiembro>/eliminar/', miembroEliminar, name='eliminar'),
    path('<int:idMiembro>/roles/', verRoles, name='ver_roles'),
    path('<int:idMiembro>/roles/<int:idRol>/asignar/', asignarRol, name='asignar_rol'),
    path('<int:idMiembro>/roles/<int:idRol>/desasignar/', desasignarRol, name='desasignar_rol'),
]

sgas/apps/proyectos/urls.py
from django.urls import path, include
from .views import ProyectoList, ProyectoCreate, ProyectoUpdate, index, createFases, updateFases, proyectoGeneral, fasesProyecto,\
    iniciarProyecto, cancelarProyecto, verFase, finalizarFase,verHistorial, asignarTI, comite, asignarComite, desasignarComite, verificarComite, finalizarProyecto, \
    crearLB, verLB, cerrarLB, crerSolicitud, interfazVotacion, votoAceptar, votoRechazar, verificarCambios, mantenerItem, cambiarItem, solicitudesProyecto, \
    reporteSolicitudes, reportes, reporteLB


urlpatterns = [
    # Enlace al menu principal de Proyectos
    path(r'', index, name='index'),
    path(r'listar/', ProyectoList.as_view(), name='listar_proyectos'),
    path(r'nuevo/', ProyectoCreate.as_view(), name='nuevo_proyecto'),
    path(r'<pk>/modificar/', ProyectoUpdate.as_view(), name='modificar_proyecto'),
    path(r'<int:id_proyecto>/', proyectoGeneral, name='general'),
    path(r'<int:id_proyecto>/iniciar/', iniciarProyecto, name='iniciar'),
    path(r'<int:id_proyecto>/finalizar/', finalizarProyecto, name='finalizar'),
    path(r'<int:id_proyecto>/cancelar/', cancelarProyecto, name='cancelar'),
    path(r'<int:id_proyecto>/fases', createFases, name='nuevas_fases'),
    path(r'<int:id_proyecto>/fases/modificar', updateFases, name='modificar_fases'),
    path(r'<int:id_proyecto>/fases/listar', fasesProyecto, name='listar_fases'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/', verFase, name='ver_fase'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/cerrar/', finalizarFase, name='cerrar_fase'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/', verLB, name='ver_lb'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/crearSolicitud/', crerSolicitud, name='crear_solicitud'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/crearLB/', crearLB, name='crear_LB'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/<int:id_lb>/cerrar/', cerrarLB, name='cerrar_LB'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/tipoItem/<int:id_tipo>/', asignarTI, name='add_tipoItem'),
    path(r'<int:id_proyecto>/comite/', comite, name='comite'),
    path(r'<int:id_proyecto>/comite/nuevo/<int:id_usuario>', asignarComite, name='asignar_comite'),
    path(r'<int:id_proyecto>/comite/eliminar/<int:id_usuario>', desasignarComite, name='desasignar_comite'),
    path(r'<int:id_proyecto>/comite/verificar/', verificarComite, name='verificar_comite'),
    path(r'<int:id_proyecto>/solicitudes/', interfazVotacion, name='solicitudes_votacion'),
    path(r'<int:id_proyecto>/solicitudes/lista/', solicitudesProyecto, name='lista_solicitudes'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/aceptar/', votoAceptar, name='solicitudes_aceptar'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/rechazar/', votoRechazar, name='solicitudes_rechazar'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/cambios/', verificarCambios, name='verificar_cambios'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/mantener/<int:id_item>/', mantenerItem, name='cambios_mantener'),
    path(r'<int:id_proyecto>/solicitudes/<int:id_solicitud>/cambiar/<int:id_item>/', cambiarItem, name='cambios_cambiar'),
    path(r'<int:id_proyecto>/historial/', verHistorial, name='ver_historial'),
    path(r'<int:id_proyecto>/reportes/', reportes, name='reportes'),
    path(r'<int:id_proyecto>/fases/<int:id_fase>/reporteLB/', reporteLB, name='reporte_LB'),
]

sgas/apps/roles/urls.py
from django.urls import path, include
from sgas.apps.roles.views import ListarRol, CrearRol, EliminarRol, EditarRol

urlpatterns = [
    path(r'listar/', ListarRol.as_view(), name='listar_roles'),
    path(r'nuevo/', CrearRol.as_view(), name='crear_rol'),
    path(r'eliminar/<int:id_rol>/', EliminarRol, name='eliminar_rol'),
    path(r'editar/<int:id_rol>/', EditarRol, name='editar_rol'),
]

sgas/apps/tipoitem/urls.py
from django.urls import path
from sgas.apps.tipoitem.views import CrearTipoItem, ListarTipoItem, listaImportar, importarTipoItem, \
    modificarTipoItem, eliminarTipoItem

urlpatterns = [
    path(r'nuevo/', CrearTipoItem, name='crear_tipoitem'),
    path(r'modificar/<int:idTipo>', modificarTipoItem, name='modificar_tipoitem'),
    path(r'eliminar/<int:idTipo>', eliminarTipoItem, name='eliminar_tipoitem'),
    path(r'', ListarTipoItem.as_view(), name='listar_tipoitem'),
    path(r'importar/', listaImportar, name='listar_importar'),
    path(r'importar/<int:idTipo>', importarTipoItem, name='importar'),

]

sgas/apps/usuarios/urls.py
from django.urls import path, include

from sgas.apps.usuarios.views import home, CrearPerfil, ListarPerfil, editarPerfil, listaAcceso, \
    concederAcceso, eliminarPerfil, administrador, proyectos_usuario, bitacora

urlpatterns = [
    path(r'home/', home, name='home'),
    path(r'nuevo/', CrearPerfil.as_view(), name='crear_perfil'),
    path(r'listar/', ListarPerfil.as_view(), name='listar_perfiles'),
    path(r'acceso/', listaAcceso, name='lista_acceso'),
    path(r'administrador/<int:id_perfil>', concederAcceso, name='conceder_acceso'),
    path(r'editar/<int:id_perfil>/', editarPerfil, name='editar_perfil'),
    path(r'eliminar/<int:id_perfil>/', eliminarPerfil, name='eliminar_perfil'),
    path(r'administrador/', administrador, name='administrador'),
    path(r'<int:id_usuario>/', proyectos_usuario, name='proyectos_usuario'),
    path(r'<int:id_usuario>/bitacora/', bitacora, name='bitacora'),
]

sgas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # En este apartado se listan las urls predefinidas para el
    # autenticador de Google y urls del SGAS.
    #
    # 1. **URL** admin
    # 2. **URL** cuentas
    # 3. **URL** de proyectos
    # 4. **URL** de usuarios
    # 5. **URL** inicio

    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('proyectos/', include(('sgas.apps.proyectos.urls', 'proyectos'), namespace='proyectos')),
    path('usuarios/', include(('sgas.apps.usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('', include('sgas.apps.proyectos.urls')),
    path('proyectos/<int:idProyecto>/miembros/', include(('sgas.apps.miembros.urls', 'miembros'), namespace='miembros')),
    path('proyectos/<int:idProyecto>/tipoitem/', include(('sgas.apps.tipoitem.urls', 'tipoitem'), namespace='tipoitem')),
    path('proyectos/<int:idProyecto>/roles/', include(('sgas.apps.roles.urls', 'roles'), namespace='roles')),
    path('proyectos/<int:idProyecto>/fases/<int:idFase>/tipoitem/<int:idTipo>/item/', include(('sgas.apps.items.urls', 'items'), namespace='items')),
    path('proyectos/<int:idProyecto>/fases/<int:idFase>/tipoitem/<int:idTipo>/item/<int:idItem>/relaciones/', include(('sgas.apps.relaciones.urls', 'relaciones'), namespace='relaciones')),
]

sgas/apps/miembros/models.py
from django.db import models
from sgas.apps.proyectos.models import Proyecto
from sgas.apps.usuarios.models import Perfil

# Create your models here.
class Miembro(models.Model):
    idPerfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    idProyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)

sgas/apps/items/forms.py
from django import forms
from django.forms import modelformset_factory
from sgas.apps.items.models import Item, CampoNumero, CampoCadena, CampoFecha, CampoArchivo
from sgas.apps.tipoitem.models import TipoItem

class ItemForm(forms.ModelForm):

    identif = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "readonly": "readonly"}))

    def __init__(self, *args, **kwargs):
        nombre = kwargs.pop('nombre')
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['identif'].initial = nombre
        self.fields['costo'].widget.attrs['min'] = 1

    def save(self, commit=True, *args, **kwargs):
        fase = kwargs.get('fase')
        nombre = kwargs.get('nombre')
        tipo = kwargs.get('tipo')
        instance = super(ItemForm, self).save(commit=False)
        instance.fase = fase
        instance.identificador = nombre
        instance.tipo = tipo
        if commit:
            instance.save()
        return instance

    #def update(self, commit=True, *args, **kwargs):
    #    fase = kwargs.get('fase')
    #    nombre = kwargs.get('nombre')
    #    tipo = kwargs.get('tipo')
    #    version = kwargs.get('version')
    #    instance = super(ItemForm, self).save(commit=False)
    #    instance.fase = fase
    #    instance.identificador = nombre + "v" + str(version)
    #    instance.tipo = tipo
    #    instance.version = version
    #    if commit:
    #        instance.save()
    #    return instance

    def update(self, commit=True, *args, **kwargs):
        fase = kwargs.get('fase')
        nombre = kwargs.get('nombre')
        tipo = kwargs.get('tipo')
        version = kwargs.get('version')
        instance = super(ItemForm, self).save(commit=False)
        instance.fase = fase
        if version == 1:
            instance.identificador = nombre + "v" + str(version+1)
        else:
            n = len(nombre)
            instance.identificador = nombre[:n-1] + str(version+1)
        instance.tipo = tipo
        instance.version = version+1
        if commit:
            instance.save()
        return instance

    class Meta:

        model = Item

        fields = [
            'descripcion',
            'costo',
        ]
        labels = {
            'descripcion': 'Descripcion',
            'costo': 'Costo',
        }
        widgets = {
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
            'costo': forms.NumberInput(attrs={'initial': 0, 'min': 1, 'max': 10})
        }

class BaseCampoNumeroForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoNumeroForm, self).__init__(*args, **kwargs)

    class Meta:

        model = CampoNumero

        fields = [
            'nombre',
            'opcional',
            'numero'
        ]

class BaseCampoCadenaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoCadenaForm, self).__init__(*args, **kwargs)
        self.fields['cadena'].required = self.fields['opcional'].initial

    class Meta:
        model = CampoCadena

        fields = [
            'nombre',
            'opcional',
            'cadena'
        ]


class BaseCampoFechaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoFechaForm, self).__init__(*args, **kwargs)
        self.fields['fecha'].required = self.fields['opcional'].initial

    class Meta:
        model = CampoFecha

        fields = [
            'nombre',
            'opcional',
            'fecha'
        ]
        widgets={
            'fecha': forms.DateInput(attrs={'class':'form-control col-4','type':'date'})
        }
class BaseCampoArchivoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseCampoArchivoForm, self).__init__(*args, **kwargs)
        self.fields['archivo'].required = self.fields['opcional'].initial

    class Meta:
        model = CampoArchivo

        fields = [
            'nombre',
            'opcional',
            'archivo'
        ]
        widgets = {
            'archivo': forms.FileInput(attrs={'class': 'custom-file'})
        }

class mensajeCorreo(forms.Form):
    mensaje = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows":"5"}))

sgas/apps/miembros/forms.py
from django import forms
from django.db.models import Q

from sgas.apps.miembros.models import Miembro
from sgas.apps.proyectos.models import Proyecto
from sgas.apps.usuarios.models import Perfil


class MiembrosForm(forms.ModelForm):

    class Meta:
            model = Miembro

            fields = [
                'idPerfil',
            ]

            labels = {
                'idPerfil': 'Perfil',
            }

            widgets = {
                'idPerfil': forms.Select(attrs={'class':'form-control custom-select'}),
            }


    def __init__(self, *args, **kwargs):
            idProyecto = kwargs.pop('idProyecto')
            super(MiembrosForm, self).__init__(*args, **kwargs)
            proyecto = Proyecto.objects.get(id=idProyecto)
            miembro = proyecto.miembro_set.all()
            perfil = Perfil.objects.all()
            valid_id = []
            for p in perfil:
                if not Miembro.objects.filter(idProyecto=proyecto).filter(idPerfil=p).exists():
                    if not p.id == 1:
                        valid_id.append(p.id)
            perfiles = Perfil.objects.filter(id__in = valid_id)
            self.fields['idPerfil'].queryset = perfiles

sgas/apps/miembros/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from sgas.apps.usuarios.models import Perfil
from sgas.apps.proyectos.models import Proyecto, Historial
from sgas.apps.miembros.models import Miembro
from sgas.apps.miembros.forms import MiembrosForm
from django.contrib.auth.models import User

# === Crear Miembro ===
@login_required
def miembroCrear(request, idProyecto):
    """
    Vista basada en funcion para crear miembros.
    Recibe un 'request' y la id de un Proyecto como parametros.
    Una vez haya terminado la peticion se retorna a la vista de Lista de Miembros.
    """
    if request.method == 'POST':
        form = MiembrosForm(request.POST, idProyecto=idProyecto)

        if form.is_valid():
            miembro = form.save(commit=False)
            miembro.idProyecto = Proyecto.objects.get(id=idProyecto)
            miembro.save()
            user = User.objects.get(username=request.user)
            perfil = Perfil.objects.get(user=user)
            Historial.objects.create(operacion='Agregar a {} al proyecto'.format(miembro.idPerfil.__str__()), autor=perfil.__str__(), proyecto=Proyecto.objects.get(id=idProyecto), categoria="Miembros")

        return redirect('miembros:lista', idProyecto=idProyecto)

    else:
        form = MiembrosForm(request.POST or None, idProyecto=idProyecto)

    return render(request, 'miembros/nuevoMiembro.html', {'form': form, 'proyecto':idProyecto})

# === Eliminar Miembro ===
@login_required
def miembroEliminar(request, idProyecto, idMiembro):
    """
    Vista basada en funcion para eliminar miembros.
    Recibe un 'request', el id de un proyecto y el id de un miembro como parametros.
    Una vez haya terminado la peticion se retorna a la vista de Lista de Miembros.
    """
    miembro = Miembro.objects.get(id=idMiembro)
    if request.method == 'POST':
        miembro.delete()
        user = User.objects.get(username=request.user)
        perfil = Perfil.objects.get(user=user)
        Historial.objects.create(operacion='Eliminar a {} del proyecto'.format(miembro.idPerfil.__str__()), autor=perfil.__str__(), proyecto=Proyecto.objects.get(id=idProyecto), categoria="Miembros")
        return redirect('miembros:lista', idProyecto=idProyecto)
    return render(request, 'miembros/eliminarMiembro.html', {'miembros':miembro, 'idProyecto':idProyecto})

# === Listar Miembros ===
@login_required
def verMiembrosEnProyecto(request, idProyecto):
    """
    Vista basada en funcion para listar miembros dentro de un proyecto.
    Recibe un 'request' y el id de un proyecto como parametros.
    """
    proyecto = Proyecto.objects.get(id=idProyecto)
    miembro = proyecto.miembro_set.all()
    perfil = Perfil.objects.all()
    valid_id = []
    for p in perfil:
        if not Miembro.objects.filter(idProyecto=proyecto).filter(idPerfil=p).exists():
            if not p.id == 1:
                valid_id.append(p.id)
    perfiles = Perfil.objects.filter(id__in = valid_id)
    #print(perfiles)
    miembro = Miembro.objects.filter(idProyecto=idProyecto)
    g = proyecto.gerente
    return render(request, 'miembros/verMiembrosEnProyecto.html', {'miembros':miembro, 'gerente':g, 'idProyecto':idProyecto, 'participantes_para_agregar':perfiles.all().count()>0})

sgas/templates/proyectos/fasesProyecto.html
{% extends 'base.html' %}
{% block content%}
<br>
<div class="container-fluid">
    <ins><h3 align="center">Fases del Proyecto</h3> </ins>
    <br>
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr class="table-primary">
                        <th>Nombre</th>
                        <th>Posición</th>
                        <th>Estado</th>
                        <th>Num. LB</th>
                        <th>Num. Ítems</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fase in fases %}
                        <tr>
                            <td><a href="{% url 'proyectos:ver_fase' fase.proyecto.id fase.id%}">{{fase.nombre}}</a></td>
                            <td>{{fase.posicion}}</td>
                            <td>{{fase.estado}}</td>
                            <td>{{fase.numLB}}</td>
                            <td>{{fase.numItems}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p align="center">
                <a class="btn btn-primary" href="{% url 'proyectos:general' proyecto %}" role="button">Volver</a>
            </p>
        </div>
        <div class="col-md-3">

        </div>
    </div>
</div>
{% endblock %}

sgas/templates/proyectos/proyectoGeneral.html
{% extends 'base.html' %}
{% load filtros_proyectos %}

{% block content %}
<br>
<div class="container-fluid">
    {% if messages %}
        {% for message in messages %}
            {% if 'error' in message.tags %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endif %}
            {% if 'info' in message.tags %}
                <div class="alert alert-dismissible alert-info" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <h2 align="center">Datos del Proyecto</h2><br>
    <div class="row">
        <div class="col-md-6">
            <ins><h3 align="center">Información General</h3></ins>
            <table class="table table-light">
                <tbody>
                    <tr>
                        <th class="table-primary">Nombre:</th>
                        <td>{{proyecto.nombre}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Descripción:</th>
                        <td>{{proyecto.descripcion}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Gerente:</th>
                        <td>{{proyecto.gerente}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Creación</th>
                        <td>{{proyecto.fechaCreacion}}</td>
                    </tr>
                    <tr>
                        <th class="table-primary">Estado:</th>
                        <td>{{proyecto.estado}}</td>
                    </tr>
                    {% if proyecto.estado == 'Iniciado' %}
                    <tr>
                        <th class="table-primary">Fecha de Inicio:</th>
                        <td>{{proyecto.fechaInicio}}</td>
                    </tr>
                    {%elif proyecto.estado == 'Finalizado' or proyecto.estado == 'Cancelado'  %}
                    <tr>
                        <th class="table-primary">Fecha de Finalización:</th>
                        <td>{{proyecto.fechaFin}}</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <ins><h3 align="center">Miembros del Proyecto</h3></ins>
            {% if miembros %}
                <table class="table">
                    <thead>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">Email</th>
                        <th scope="col">CI</th>
                        <th scope="col">Teléfono</th>
                    </thead>
                    <tbody>
                        {% for miembro in miembros %}
                        <tr>
                            <td>{{miembro.idPerfil.user.first_name}}</td>
                            <td>{{miembro.idPerfil.user.last_name}}</td>
                            <td>{{miembro.idPerfil.user.email}}</td>
                            <td>{{miembro.idPerfil.ci}}</td>
                            <td>{{miembro.idPerfil.telefono}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>El proyecto aún no cuenta con miembros asociados</h4>
            {% endif %}
        </div>
    </div>
    <div class="row" align="right">

        <div class="col-md-12">
            {% if solicitudes %}
                <a href="{% url 'proyectos:lista_solicitudes' proyecto.id %}" class="btn btn-primary">Resolver Solicitud de Cambio</a>
            {% elif fases %}

                {% if proyecto.estado == 'Pendiente' and user.id == proyecto.gerente.user.id%}
                    <a href="{% url 'proyectos:iniciar' proyecto.id %}" class="btn btn-success" role="button">Iniciar</a>
                {% endif %}
                <a href="{% url 'proyectos:listar_fases' proyecto.id %}" class="btn btn-primary" role="button">Fases</a>
                {% if request.user|pertenece_grupo:proyecto.id and proyecto.estado == 'Iniciado' %}
                    <a href="{% url 'proyectos:solicitudes_votacion' proyecto.id %}" class="btn btn-primary" role="button">Solicitudes</a>
                {% endif %}
                {% if user.id == proyecto.gerente.user.id and not proyecto.estado == 'Finalizado' and not proyecto.estado == 'Cancelado' %}
                    <a href="{% url 'miembros:lista' proyecto.id %}" class="btn btn-primary" role="button">Miembros</a>
                    <a href="{% url 'proyectos:comite' proyecto.id %}" class="btn btn-primary" role="button">Comité de Cambios</a>
                    <a href="{% url 'tipoitem:listar_tipoitem' proyecto.id %}" class="btn btn-primary" role="button">Tipos de Ítem</a>
                    <a href="{% url 'roles:listar_roles' proyecto.id %}" class="btn btn-primary" role="button">Roles</a>
                    <a href="{% url 'proyectos:cancelar' proyecto.id %}" class="btn btn-warning" role="button">Cancelar</a>
                {% endif %}
                {% if proyecto.estado == 'Iniciado' and user.id == proyecto.gerente.user.id%}
                    <a href="{% url 'proyectos:finalizar' proyecto.id %}" class="btn btn-danger" role="button">Finalizar</a>
                {% endif %}
                <a href="{% url 'proyectos:ver_historial' proyecto.id %}" class="btn btn-info" role="button">Historial</a>
                {% if user.id == proyecto.gerente.user.id %}
                    <a href="{% url 'proyectos:reportes' proyecto.id %}" class="btn btn-info" role="button">Reportes</a>
                {% endif %}
            {% else %}
                <a href="{% url  'proyectos:modificar_proyecto' proyecto.id %}" class="btn btn-primary">Configurar Proyecto</a>
            {% endif %}
        </div>
    </div>
    <br>
</div>

{% endblock %}

sgas/templates/proyectos/solicitudes.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container-fluid">
    <ins><h3 align="center">Solicitudes de Cambio</h3></ins>

    {% if  solicitudes %}
        {% for solicitud in solicitudes %}
            <div class="row">
                <div class="col-md-3">

                </div>
                <div class="col-md-6">
                    <div class="card border-primary mb-3" >
                        <div class="card-header"><b>{{solicitud.nombre}}</b></div>
                    <div class="card-body">
                        <h4 class="card-title">Línea Base: {{solicitud.lb.nombre}}</h4>
                        <p class="card-text">
                            <b>Responsable:</b> {{solicitud.responsable.first_name}} {{solicitud.responsable.last_name}}
                            <br>
                            <b>Ítems involucrados</b>:
                            {% for item in solicitud.items.all %}
                                <a href="{% url 'items:ver_item' idProyecto solicitud.lb.fase.id item.tipo.id item.id %}" >{{item.identificador}}&nbsp;&nbsp;</a>
                            {% endfor %}
                            <br>
                            <b>Motivo:</b>
                            {{solicitud.motivo}}
                        </p>
                        <p align="right">
                            <a href="{% url 'proyectos:solicitudes_aceptar' solicitud.lb.fase.proyecto.id solicitud.id %}" class="btn btn-success">Aceptar</a>
                            <a href="{% url 'proyectos:solicitudes_rechazar' solicitud.lb.fase.proyecto.id solicitud.id %}" class="btn btn-danger">Rechazar</a>
                        </p>
                    </div>
                </div>
                </div>
                <div class="col-md-3">

                </div>
            </div>
        {% endfor %}
    {% else %}
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4">
            <h4>Todas las solicitudes han sido atendidas.</h4>
        </div>
        <div class="col-md-4">

        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <p align="center">
                <a class="btn btn-primary" href="{% url 'proyectos:general' idProyecto %}">Volver</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}